title: Long Haul
description: Long Form Jekyll theme built with SASS

url: https://long-haul.netlify.app
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  title: ':title - page :num'
  trail: 
    before: 2
    after: 2
  indexpage: 'index'

navigation:
    - title: Home
      url: /
    - title: About
      url: /about
    - title: tags
      url: /tags
    - title: Contact
      url: /contact

social:
    github: brianmaierjr
    twitter: brianmaierjr
    facebook: brianmaierjr
    email: brimaidesigns@gmail.com
    linkedin: brianmaierjr

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
